name: "Bug Report"
description: Report bugs
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []
body:
    - type: markdown
      attributes:
          value: |
              Please do not disclose public security vulnerabilities here. For security issues, read SECURITY.md.
    - type: input
      id: version
      attributes:
          label: Affected Version(s)
          description: e.g., Norr.PerformanceMonitor 1.2.3, Attribution 1.0.0
          placeholder: "Norr.PerformanceMonitor x.y.z"
      validations:
          required: true
    - type: textarea
      id: description
      attributes:
          label: Description
          description: Summarize the bug.
          placeholder: "Expected behavior / Actual behavior"
      validations:
          required: true
    - type: textarea
      id: repro
      attributes:
          label: Steps to Reproduce
          description: Include a minimal reproduction (gist, repo link, or code snippet).
          render: shell
          placeholder: |
              1. ...
              2. ...
              3. ...
      validations:
          required: true
    - type: textarea
      id: logs
      attributes:
          label: Logs / Exceptions
          description: Include relevant logs and stack traces.
          render: text
    - type: dropdown
      id: os
      attributes:
          label: Operating System
          options:
              - Windows
              - Linux
              - macOS
              - Other
    - type: input
      id: dotnet
      attributes:
          label: .NET SDK/Runtime Version
          placeholder: "Output of dotnet --info"
    - type: checkboxes
      id: checks
      attributes:
          label: Checklist
          options:
              - label: I have verified there is no existing issue for the same problem
                required: true
              - label: I have included a minimal reproducible example
                required: true
              - label: I have read SECURITY.md and this is not a security vulnerability
                required: true